config/routes.rb
SwitchNotifySms::Application.routes.draw do

  resources :notifiers
  
  root :to => "notifiers#new"

get "/notify" => "notification#new"

get "/log" => "notification#view_log", :as => :logs

end

app/models/log.rb
class Log < ActiveRecord::Base
  attr_accessible :from, :from_city, :from_country, :from_state, :message, :notify_result, :to
  
  belongs_to :notifier 
  
end

app/models/notifier.rb
class Notifier < ActiveRecord::Base
  attr_accessible :device_id, :twilio_id
  
  validates :device_id,  :presence => true
  validates :twilio_id,  :presence => true
    
  has_many :logs, :dependent => :delete_all 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/notification_controller.rb
class NotificationController < ApplicationController

require 'rest_client'


def new
  
  notifiers = Notifier.find_all_by_twilio_id(params[:AccountSid])
  
  urls = []
  
  if notifiers.any?
  
  notifiers.each do |device|
     send_notification(device)
  
     log = Log.new
     
     log.notifier_id = device.id
     
     log.to = params[:To]
     log.from = params[:From]
     log.from_country = params[:FromCountry]
     log.from_city = params[:FromCity]
     log.from_state = params[:FromState]
     log.message = params[:Body]
     log.notify_result = @result
     log.save

     urls <<  'http://swtch.co/device/'+device.device_id+'/pulse'
     
  end
    render :text => urls
  else  
    render :text => '<?xml version="1.0" encoding="UTF-8" ?>   
    <Response>
        <Sms>no device defined for alerts.</Sms> 
    </Response>'
  end
end

def send_notification(device)

RestClient.get('http://swtch.co/device/'+device.device_id+'/pulse') do |response|
  if response.code == 200
    @result = "Success"
  else 
    @result = "failed with #{response.code}"
  end
end

end

def view_log
  @logs = Log.all(:order => "created_at DESC")
  
  respond_to do |format|
    format.html # index.html.erb
    format.json { render json: @logs }
  end
  
end

end

app/controllers/notifiers_controller.rb
class NotifiersController < ApplicationController
  # GET /notifiers
  # GET /notifiers.json
  def index
    @notifiers = Notifier.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notifiers }
    end
  end

  # GET /notifiers/1
  # GET /notifiers/1.json
  def show
    @notifier = Notifier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notifier }
    end
  end

  # GET /notifiers/new
  # GET /notifiers/new.json
  def new
    @notifier = Notifier.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notifier }
    end
  end

  # GET /notifiers/1/edit
  def edit
    @notifier = Notifier.find(params[:id])
  end

  # POST /notifiers
  # POST /notifiers.json
  def create
    @notifier = Notifier.new(params[:notifier])

    respond_to do |format|
      if @notifier.save
        format.html { redirect_to logs_path, notice: 'Notifier was successfully created. Hit refresh to see any new activity' }
        format.json { render json: @notifier, status: :created, location: @notifier }
      else
        format.html { render action: "new" }
        format.json { render json: @notifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notifiers/1
  # PUT /notifiers/1.json
  def update
    @notifier = Notifier.find(params[:id])

    respond_to do |format|
      if @notifier.update_attributes(params[:notifier])
        format.html { redirect_to @notifier, notice: 'Notifier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifiers/1
  # DELETE /notifiers/1.json
  def destroy
    @notifier = Notifier.find(params[:id])
    @notifier.destroy

    respond_to do |format|
      format.html { redirect_to notifiers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/helpers/notifiers_helper.rb
module NotifiersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwitchNotifySms</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Cantora+One' rel='stylesheet' type='text/css'>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/notification/view_log.html.erb
<h1>Activity Log</h1>

<p id="notice"><%= notice %></p>
<div class = "datagrid">
<table>
	<thead><tr>
		<th>From</th>
		<th>Sender Location</th>
		<th>To</th>
		<th>Message</th>
		<th>Received</th>
		<th>Device</th>
		<th>Status</th>
	</tr></thead>
	<% @logs.each do |log| %>
	<tbody>
	<tr  class="<%= cycle("", "alt") %>">
		<td><%= log.from %></td>
		<td><%= "#{log.from_city}, #{log.from_state}" %></td>
		<td><%= log.to %></td>
		<td><%= log.message %></td>
		<td><%= time_ago_in_words(log.created_at) %> ago</td>
		<td><%= log.notifier.device_id %></td>
		<td><%= log.notify_result %></td>
	</tr>
	</tbody>	
	<% end %>
</table>
</div>

app/views/notifiers/_form.html.erb
<%= form_for(@notifier) do |f| %>
  <% if @notifier.errors.any? %>
    <div class="error_explanation">
      <h2>Couldn't create notifier - <%= pluralize(@notifier.errors.count, "field") %> need fixing:</h2>

      <ul>
      <% @notifier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "What's your Twilio Account ID?" %><br />
    <%= f.text_field :twilio_id, :placeholder => "Twilio Account ID", :class => 'field'  %>
  </div>
  <div class="field">
    <%= f.label :name, "What light do you want to flash?" %><br />
    <%= f.text_field :device_id, :placeholder => "Switch Device ID", :class => 'field' %>
  </div>
  <div class="actions">
    <%= f.submit "Create", :class => 'button' %>
  </div>
<% end %>

app/views/notifiers/edit.html.erb
<h1>Editing notifier</h1>

<%= render 'form' %>

<%= link_to 'Show', @notifier %> |
<%= link_to 'Back', notifiers_path %>

app/views/notifiers/index.html.erb
<h1>Listing notifiers</h1>

<div class = "datagrid">
<table>
	<thead>
  <tr>
    <th>Twilio</th>
    <th>Device</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>

<% @notifiers.each do |notifier| %>
<tbody>
  <tr  class="<%= cycle("", "alt") %>">
    <td><%= notifier.twilio_id %></td>
    <td><%= notifier.device_id %></td>
    <td><%= link_to 'Show', notifier %></td>
    <td><%= link_to 'Edit', edit_notifier_path(notifier) %></td>
    <td><%= link_to 'Destroy', notifier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
</tbody>
<% end %>
</table>
</div>

<br />

<%= link_to 'New Notifier', new_notifier_path %>

app/views/notifiers/new.html.erb
<h1>Setup SMS Notifications</h1>
<div class = "new-form">
<%= render 'form' %>
</div>
<div class="centered">
<p>Already setup? You can <%= link_to "Check activity", logs_path  %> or <%= link_to "Manage Existing Notifiers", notifiers_path  %></p>

<%= link_to(image_tag("switch_logo.png"), "http://www.switchdevices.com", :class=> "logo") %>
</div>

app/views/notifiers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Twilio:</b>
  <%= @notifier.twilio_id %>
</p>

<p>
  <b>Device:</b>
  <%= @notifier.device_id %>
</p>


<%= link_to 'Edit', edit_notifier_path(@notifier) %> |
<%= link_to 'Back', notifiers_path %>